#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page


echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
        return 404 \"Ceci n'est pas une page\";
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Create the custom 404 page content
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx restart
